package game.functions.range;

import java.util.BitSet;

import game.Game;
import game.functions.ints.IntFunction;
import game.types.state.GameType;
import other.context.Context;

/**
 * Returns a range.
 * 
 * @author cambolbro and Eric.Piette
 */

// **
// ** Do not @Hide, or loses mapping in grammar!
// **

public interface RangeFunction extends GameType
{
	/**
	 * @param context The context.
	 * @return The range generated by this context.
	 */
	public Range eval(final Context context);

	/** 
	 * @return Function for the minimum of the range. 
	 */
	public IntFunction minFn();
	
	/** 
	 * @return Function for the maximum of the range. 
	 */
	public IntFunction maxFn();

	/**
	 * @param game The game.
	 * @return Accumulated flags corresponding to the game concepts.
	 */
	public BitSet concepts(final Game game);

	/**
	 * @return Accumulated flags corresponding to read data in EvalContext.
	 */
	public BitSet readsEvalContextRecursive();

	/**
	 * @return Accumulated flags corresponding to write data in EvalContext.
	 */
	public BitSet writesEvalContextRecursive();

	/**
	 * @param game The game.
	 * @return True if a required ludeme is missing.
	 */
	public boolean missingRequirement(final Game game);

	/**
	 * @param game The game.
	 * @return True if the ludeme can crash the game during its play.
	 */
	public boolean willCrash(final Game game);
}
